<?xml version="1.0" encoding="utf-8"?><Database Name="PrototipoSimuladores" Class="TabelasDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=TECNOLOGIA01-PC\SQLEXPRESS;Initial Catalog=PrototipoSimuladores;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="PrototipoSimuladoresConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Plano" Member="dcPlanos">
    <Type Name="dcPlanos">
      <Column Name="PlanoId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Descricao" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Parametros" Member="dcParametros">
    <Type Name="dcParametros">
      <Column Name="ParametrosId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nome" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="descricao" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>