#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PrototipoSimuladores")]
public partial class TabelasDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertdcPlanos(dcPlanos instance);
  partial void UpdatedcPlanos(dcPlanos instance);
  partial void DeletedcPlanos(dcPlanos instance);
  partial void InsertdcParametros(dcParametros instance);
  partial void UpdatedcParametros(dcParametros instance);
  partial void DeletedcParametros(dcParametros instance);
  #endregion
	
	public TabelasDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["PrototipoSimuladoresConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public TabelasDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public TabelasDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public TabelasDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public TabelasDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<dcPlanos> dcPlanos
	{
		get
		{
			return this.GetTable<dcPlanos>();
		}
	}
	
	public System.Data.Linq.Table<dcParametros> dcParametros
	{
		get
		{
			return this.GetTable<dcParametros>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Plano")]
public partial class dcPlanos : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _PlanoId;
	
	private string _Descricao;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPlanoIdChanging(int value);
    partial void OnPlanoIdChanged();
    partial void OnDescricaoChanging(string value);
    partial void OnDescricaoChanged();
    #endregion
	
	public dcPlanos()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlanoId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int PlanoId
	{
		get
		{
			return this._PlanoId;
		}
		set
		{
			if ((this._PlanoId != value))
			{
				this.OnPlanoIdChanging(value);
				this.SendPropertyChanging();
				this._PlanoId = value;
				this.SendPropertyChanged("PlanoId");
				this.OnPlanoIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descricao", DbType="NVarChar(50)")]
	public string Descricao
	{
		get
		{
			return this._Descricao;
		}
		set
		{
			if ((this._Descricao != value))
			{
				this.OnDescricaoChanging(value);
				this.SendPropertyChanging();
				this._Descricao = value;
				this.SendPropertyChanged("Descricao");
				this.OnDescricaoChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Parametros")]
public partial class dcParametros : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ParametrosId;
	
	private string _nome;
	
	private string _descricao;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnParametrosIdChanging(int value);
    partial void OnParametrosIdChanged();
    partial void OnnomeChanging(string value);
    partial void OnnomeChanged();
    partial void OndescricaoChanging(string value);
    partial void OndescricaoChanged();
    #endregion
	
	public dcParametros()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParametrosId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ParametrosId
	{
		get
		{
			return this._ParametrosId;
		}
		set
		{
			if ((this._ParametrosId != value))
			{
				this.OnParametrosIdChanging(value);
				this.SendPropertyChanging();
				this._ParametrosId = value;
				this.SendPropertyChanged("ParametrosId");
				this.OnParametrosIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nome", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string nome
	{
		get
		{
			return this._nome;
		}
		set
		{
			if ((this._nome != value))
			{
				this.OnnomeChanging(value);
				this.SendPropertyChanging();
				this._nome = value;
				this.SendPropertyChanged("nome");
				this.OnnomeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descricao", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
	public string descricao
	{
		get
		{
			return this._descricao;
		}
		set
		{
			if ((this._descricao != value))
			{
				this.OndescricaoChanging(value);
				this.SendPropertyChanging();
				this._descricao = value;
				this.SendPropertyChanged("descricao");
				this.OndescricaoChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
